CREATE TABLE fanout_rule (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    sort_order NUMBER(10) NOT NULL,
    match_type VARCHAR2(30) NOT NULL,
    url_pattern VARCHAR2(2000) NOT NULL,
    timeout_ms NUMBER(10) DEFAULT 60000 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_fanout_rule_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_fanout_rule_match_type CHECK (match_type IN ('REGEX', 'STARTS_WITH'))
);

CREATE TABLE fanout_target (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id NUMBER NOT NULL,
    target_url VARCHAR2(2000) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    sort_order NUMBER(10) NOT NULL,
    CONSTRAINT fk_fanout_target_rule FOREIGN KEY (rule_id) REFERENCES fanout_rule(id) ON DELETE CASCADE,
    CONSTRAINT chk_fanout_target_enabled CHECK (enabled IN (0, 1))
);

CREATE INDEX idx_fanout_rule_enabled_order ON fanout_rule(enabled, sort_order, id);
CREATE INDEX idx_fanout_target_rule_order ON fanout_target(rule_id, enabled, sort_order, id);
